# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Build settings
# remote_theme:  bit-ranger/blog

plugins:
  - jekyll-feed
  - [jekyll-paginate]


permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "page/:num"
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]

title: Eric's Site
email: ericxiang456@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericzhang456.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ericxiang456
github:
  username: ericzhang456
# swiftype:
#   searchId: 
gitment:
  repo: ericzhang456.github.io
  client_id: 3fb2a45b1da16cadb27d
  client_secret: 12d62716dda3ce7e9686b37a8c04cd30f7805a4d

imgrepo: "https://ericzhang456.github.io/static/img"

# Google Analytics
google_analytics: UA-97021912-1 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
